travis:
  secure:
    BINSTAR_TOKEN: ki4B/Syf4ky/sOcDL/hNlppyQEpVBU0DNhZy0ifEZLMmRNiHTUXvzEcb0RptAeDAiIybh8/qBmYkkClXytQmAEtPO/cKI6XGlRyGyXG31gMm9wa3muLKan5p1KZmlOFE+CzOlWB8EqRuOFdTlrLl7qDsVrLokfbXuzOG2Mg8WvLzEeZmOmIHB9i2FTkYBo3wX0iJWM8Tl+bsrRfyhc/YaFdsJACmA1/i9BNJP1JHSSCT823pJO5mOCeQ93svzC5nkofxAJmj4IqfsHHcrS+zVlFiz9zWdRXM/ovSi7E2F6oIy44yenjRG7ujLuInQrlel4R+H8dT63PEu1TgkGxjwwHtKQJaYv5tUD6kCHrWzDGTtBoS+ebjFDlliY7dgZP2sRCN/zU50krZ94ZdMx/+XnJzvJ5vElH/Sjqg/lkUk0mlN3NoH8+2mjGWLIqP/FY2F+SQFlXx4HVt9pHb0NxHrluGjYzB4P6b/ATgTwXaOzQ183A7yigCnfo6Ka3epJ9iwuQUYsvbIukL1LnN5GPdtqF/P5RUadINvmWV/0Ew84wE03jfzXyisYEWTQzD2cbquB/I5MfasHGqbaey+MLcCbRkz2L7Pi0tpdCARt+Y5yzqoZqjwkc9vgjv4si5pSHYq13apT/oRuM8TCN2XEzx/J7N7/EE76c+fSdkZ05NFFI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
